import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import NavBar from '@/components/nav-bar'
import Script from 'next/script'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Caye's Portfolio",
  icons: {
    icon: '/caye-pc.png',
  }
  //description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <Script src="https://umami.iamcaye.com/script.js" data-website-id="05fc82e0-3b27-4b80-a434-84abbd183131" />
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
